/*
 * This source file was generated by the Gradle 'init' task
 */
package module;

import module.Core.Collections.GenericHashSet;

public class App {
    public static void main(String[] args) {
        GenericHashSet collection = new GenericHashSet();
        collection.put("Тыква");
        collection.put("Арбуз");
        collection.put("Тыква");


        System.out.println("Size is:" + collection.size());

        System.out.println("Element retrived:" + collection.get(11));

        collection.remove("Арбуз");
        System.out.println("Size after removing is:" + collection.size());
    }
}
