spring:
  application:
    name: gateway-service

server:
  port: 8080
  netty:
    idle-timeout: 10s
    connection-timeout: 10s

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka}